// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; 

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADGtxZtgo7sFACkNGUukA30dhkvAJkao4',
    appId: '1:1003542709243:web:0df6d9ede9d12d9d38015e',
    messagingSenderId: '1003542709243',
    projectId: 'flutter-project-1fa07',
    authDomain: 'flutter-project-1fa07.firebaseapp.com',
    storageBucket: 'flutter-project-1fa07.firebasestorage.app',
    measurementId: 'G-GKXYZWPXC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv_AzK5s4NOHPlsulz0P_m5xAzle5z5BE',
    appId: '1:1003542709243:android:8fbf30adae79ebc638015e',
    messagingSenderId: '1003542709243',
    projectId: 'flutter-project-1fa07',
    storageBucket: 'flutter-project-1fa07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOQNF3qKDGVvfbABFRA2xz5HRSqG3aP4',
    appId: '1:1003542709243:ios:af5a648babd6485338015e',
    messagingSenderId: '1003542709243',
    projectId: 'flutter-project-1fa07',
    storageBucket: 'flutter-project-1fa07.firebasestorage.app',
    iosBundleId: 'com.example.latihan111pplg2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOOQNF3qKDGVvfbABFRA2xz5HRSqG3aP4',
    appId: '1:1003542709243:ios:af5a648babd6485338015e',
    messagingSenderId: '1003542709243',
    projectId: 'flutter-project-1fa07',
    storageBucket: 'flutter-project-1fa07.firebasestorage.app',
    iosBundleId: 'com.example.latihan111pplg2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADGtxZtgo7sFACkNGUukA30dhkvAJkao4',
    appId: '1:1003542709243:web:3de03a4a573dc2da38015e',
    messagingSenderId: '1003542709243',
    projectId: 'flutter-project-1fa07',
    authDomain: 'flutter-project-1fa07.firebaseapp.com',
    storageBucket: 'flutter-project-1fa07.firebasestorage.app',
    measurementId: 'G-DNCMPN70PV',
  );

}